---
  collections:
    - name: middleware_automation.wildfly
    - name: middleware_automation.jws
    - name: middleware_automation.common_criteria
    - name: community.docker
    - name: community.general