---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/requirements.yml
driver:
  name: podman
platforms:
  - name: instance
    image: registry.access.redhat.com/ubi8/ubi-init:latest
    pre_build_image: true
    privileged: true
    command: "/usr/sbin/init"
    packages:
      - sudo
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    prepare: prepare.yml
    verify: ../../playbooks/wildfly.yml
    vars:
      ansible_distribution: 'RedHat'
  inventory:
    host_vars:
      hosts_group_name: all
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    #- idempotence
    - side_effect
    - verify
    - cleanup
    - destroy