---
- name: "Converge"
  hosts: all
  vars_files:
    - ../../playbooks/vars.yml
  collections:
    - middleware_automation.jws
    - middleware_automation.wildfly
    - middleware_automation.common_criteria
  roles:
    - jws
    - jws_common_criteria
    - wildfly_install
    - wildfly_systemd
    - wildfly_common_criteria