---
- name: "Validate Common Criteria recommendations on Wildfly installation"
  hosts: all
  vars_files:
    - vars.yml

  collections:
    - middleware_automation.wildfly
    - middleware_automation.common_criteria
  roles:
    - wildfly_install
    - wildfly_systemd
    - wildfly_common_criteria

  pre_tasks:
    - name: Create directory for WildFly
      ansible.builtin.file:
        path: "{{ wildfly_home }}"
        state: directory
        mode: "0755"

    - package:
        name: "{{ item }}"
        state: present
      loop:
        - unzip
        - tar
        - java-1.8.0-openjdk

  post_tasks:
    - name: "Ensure user {{ wildfly_user }} exists."
      ansible.builtin.user:
        name: "{{ wildfly_user }}"
        groups: "{{ wildfly_group }}"
        state: present

    - name: "Ensure group {{ wildfly_group }} exists."
      ansible.builtin.group:
        name: "{{ wildfly_group }}"
        state: present

    - name: "Start server"
      command: "{{ wildfly_home }}/bin/standalone.sh"
      register: out
      async: 15
      poll: 0

    - wait_for:
        timeout: 10

    - debug:
        msg: "{{ out }}"
        
    - wait_for:
        port: 8080

    - name: "Checks that Wildfly server is running and accessible"
      get_url:
        url: http://localhost:8080/
        dest: '/dev/null'
