---
- name: "Validate Common Criteria recommendations on Tomcat installation"
  hosts: all
  vars_files:
    - vars/tomcat.yml
  tasks:
    - name: "Ensure Tomcat is started and listen to appropriate port"
      ansible.builtin.wait_for:
        host: "{{ override_tomcat_listen_http_bind_address }}"
        port: "{{ override_tomcat_listen_http_port | default(8080) }}"
      when:
        - tomcat_systemd_enabled is defined