---
#tomcat vars
jws_setup: true
tomcat_version: 9.0.50
download_url: https://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.zip
jws_install_dir: /opt
tomcat_zipfile: "{{ jws_install_dir }}/tomcat.zip"
jws_home: "{{ jws_install_dir }}/apache-tomcat-{{ tomcat_version }}"
jws_java_version: 1.8.0
jws_listen_http_bind_address: 127.0.0.1
jws_listen_http_port: 8081

#wildfly vars
install_name: "{{ override_install_name | default('wildfly') }}"
wildfly_user: "{{ install_name }}"
wildfly_group: "{{ install_name }}"
wildfly_config_base: standalone-ha.xml
wildfly_version: '31.0.1.Final'
wildfly_install_workdir: '/opt/wildfly/'
wildfly_home: "{{ wildfly_install_workdir }}wildfly-{{ wildfly_version }}/"
wildfly_java_home: '/usr/lib/jvm/jre-openjdk/'
wildfly_java_version: 11
wildfly_java_package_name: "java-{{ wildfly_java_version }}-openjdk-headless"
